### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by paulfeakins** [frankmarazita/GoogleSearchEmailScraper#2]
Doesn't work:

```
python3 search.py 
Name: Whitehead Legal
Timeout
------------------------------------------------------------
Name: Ferdinand Zito Associates
Timeout
------------------------------------------------------------
Name: Nanscawen Lawyers
Timeout
------------------------------------------------------------
Name: Schembri Lawyers
Timeout
------------------------------------------------------------
Name: Nicholas James Lawyers
Timeout
------------------------------------------------------------
Name: Hartleys Lawyers
Timeout
------------------------------------------------------------
```

**Comment by frankmarazita** [comment]
Sorry, I deleted your previous issue because you didn't give any info on your inputs or Python package versions. If you raise another issue I can try help you.

**Comment by paulfeakins** [comment]
No worries but it was the weekend.

paul@home:~$ python3 --version
Python 3.8.5

paul@home:~$ python3 -m pip freeze
apt-clone==0.2.1
apturl==0.5.2
bcrypt==3.2.0
beautifulsoup4==4.8.2
blinker==1.4
Brlapi==0.7.0
catfish==1.4.13
ccsm==0.9.14.1
certifi==2020.6.20
cffi==1.14.5
chardet==3.0.4
Click==7.0
colorama==0.4.3
command-not-found==0.3
compizconfig-python==0.9.14.1
configobj==5.0.6
configparser==5.0.2
crayons==0.4.0
cryptography==2.8
cupshelpers==1.0
cycler==0.10.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
distro-info===0.23ubuntu1
dnspython==2.1.0
email-validator==1.1.2
entrypoints==0.3
Flask==1.1.2
Flask-Bcrypt==0.7.1
Flask-Login==0.5.0
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
google==3.0.0
grpcio==1.16.1
httplib2==0.14.0
idna==2.8
ifaddr==0.1.6
IMDbPY==6.8
itsdangerous==1.1.0
Jinja2==2.11.3
keyring==18.0.1
kiwisolver==1.3.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
louis==3.12.0
Mako==1.1.0
MarkupSafe==1.1.0
matplotlib==3.3.3
menulibre==2.2.1
mugshot==0.4.2
netifaces==0.10.4
nose==1.3.7
numpy==1.19.5
oauthlib==3.1.0
onboard==1.4.1
packaging==20.3
pandas==1.2.1
pexpect==4.6.0
Pillow==7.0.0
protobuf==3.6.1
psutil==5.5.1
pycairo==1.16.2
pycparser==2.19
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.2
Pygments==2.3.1
PyGObject==3.36.0
PyICU==2.4.2
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyparsing==2.4.6
pyparted==3.11.2
python-apt==2.0.0+ubuntu0.20.4.4
python-dateutil==2.8.1
python-debian===0.1.36ubuntu1
python-xapp==2.0.2
pytz==2020.5
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.24.0
requests-file==1.4.3
requests-unixsocket==0.2.0
SecretStorage==2.3.1
selenium==3.141.0
setproctitle==1.1.10
simplejson==3.16.0
six==1.11.0
soupsieve==1.9.5
SQLAlchemy==1.3.23
systemd-python==234
tifffile==2021.2.1
tldextract==2.2.1
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
uk-covid19==1.2.0
urllib3==1.25.8
wadllib==1.3.3
webdriver-manager==3.3.0
Werkzeug==1.0.1
WTForms==2.3.3
xkit==0.0.0
zeroconf==0.24.4

**Comment by frankmarazita** [comment]
I can't see there being an immediate issue with your package versions. Could you try logging the error being thrown.

**Comment by paulfeakins** [comment]
Before I reinstall it and start adding logging code, perhaps you could confirm it works on your end still as I tried about 10 similar tools and all were broken so perhaps Google did an update to block them?

**Comment by frankmarazita** [comment]
Yes it definitely still works on my end. I have run it on multiple machines with no error such as yours.

**Comment by paulfeakins** [comment]
Thanks for checking, I'm in the UK (GMT) and should be able to take another look later today.

**Comment by paulfeakins** [comment]
$ python3 search.py 
Name: Whitehead Legal
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://www.whiteheadlegal.com.au/contact

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "search.py", line 31, in <module>
    data = requests.get(domain, timeout=TIMEOUT)
  File "/home/paul/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/paul/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/paul/.local/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/paul/.local/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/home/paul/.local/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/home/paul/.local/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://www.whiteheadlegal.com.au/contact

**Comment by paulfeakins** [comment]
I got it working by removing all packages as described here:
https://stackoverflow.com/questions/11248073/what-is-the-easiest-way-to-remove-all-packages-installed-by-pip

Must have been some conflict with another package. Thanks for your help, seems like a great tool.
